feat: show the logs of errored tasks
Signed-off-by: Alex Collins <alex_collins@intuit.com>

diff --git a/tasks.yaml b/tasks.yaml
--- a/tasks.yaml
+++ b/tasks.yaml
@@ -37,7 +37,14 @@ spec:
     - mountPath: /work
       name: work
   - name: error
-    command: exit 1
+    command:
+    - sh
+    - -c
+    - |
+      echo "hello" >&2
+      echo "I'm an error" >&2
+      sleep 3s
+      exit 1
   - name: script
     command:
       - sh
